In [5]:
import numpy as np

## Identity matrix
Diagonal elements are 1, all other are 0

In [2]:
np.eye(3)

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [3]:
arr = np.eye(5)

In [4]:
arr

array([[1., 0., 0., 0., 0.],
       [0., 1., 0., 0., 0.],
       [0., 0., 1., 0., 0.],
       [0., 0., 0., 1., 0.],
       [0., 0., 0., 0., 1.]])

## Diagonal matrix
Diagonal matrix are non-0, rest are 0

In [6]:
np.diag([1,2,3,4,5])

array([[1, 0, 0, 0, 0],
       [0, 2, 0, 0, 0],
       [0, 0, 3, 0, 0],
       [0, 0, 0, 4, 0],
       [0, 0, 0, 0, 5]])

In [8]:
diag_mtrx = np.diag((1,2,3))

In [9]:
diag_mtrx

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [10]:
np.diag(diag_mtrx)

array([1, 2, 3])

## Random elements

In [17]:
# Random numbers from uniform distribution
np.random.rand(4)

array([0.17546927, 0.61970152, 0.13450842, 0.79142245])

In [18]:
# Random numbers from normal/Gaussian distribution
np.random.randn(6)

array([-0.34194384, -0.69910319, -0.12392639, -0.45095598,  1.05573889,
       -1.56822833])

## Check if 2 arrays share memory location

In [19]:
arr1 = np.arange(10)
arr1

array([0, 1, 2, 3, 4, 5, 6, 7, 8, 9])

In [20]:
arr2 = arr1[:5]
arr2

array([0, 1, 2, 3, 4])

In [21]:
np.shares_memory(arr1,arr2)

True

In [22]:
# Create different memoery address for arr3 i.e. deep copy arr1
arr3 = arr1[:5].copy()
arr3

array([0, 1, 2, 3, 4])

In [23]:
np.shares_memory(arr1,arr3)

False

## Operations on numpy arrays

In [25]:
# scalar addition
a = np.array([1,2,3])
type(a)

numpy.ndarray

In [26]:
b = np.arange(10)
type(b)

numpy.ndarray

In [27]:
a+1

array([2, 3, 4])

In [28]:
a+5

array([6, 7, 8])

In [29]:
a

array([1, 2, 3])

In [30]:
# vector addition

In [34]:
a+b # cannot add vectors of different shapes

ValueError: operands could not be broadcast together with shapes (3,) (10,) 

In [35]:
arr1 = np.array([1,2,3,4,5])
arr2 = np.array([6,7,8,9,10])

In [36]:
arr1+arr2

array([ 7,  9, 11, 13, 15])

In [37]:
# Matrix addition

mat1 = np.eye(3)
mat1

array([[1., 0., 0.],
       [0., 1., 0.],
       [0., 0., 1.]])

In [38]:
mat2 = np.diag([1,2,3])
mat2

array([[1, 0, 0],
       [0, 2, 0],
       [0, 0, 3]])

In [39]:
mat1+mat2

array([[2., 0., 0.],
       [0., 3., 0.],
       [0., 0., 4.]])

In [40]:
mat1*mat2

array([[1., 0., 0.],
       [0., 2., 0.],
       [0., 0., 3.]])

In [41]:
mat2 * mat2

array([[1, 0, 0],
       [0, 4, 0],
       [0, 0, 9]])

In [42]:
# Array comparison

mat1 == mat2 # element wise comparison

array([[ True,  True,  True],
       [ True, False,  True],
       [ True,  True, False]])

In [43]:
mat3 = np.diag([1,2,3])
mat4 = np.diag([3,4,5,6])

In [45]:
mat3 == mat4 # comparison of arrays of different shapes

<ipython-input-45-81837fa4c538>:1: DeprecationWarning: elementwise comparison failed; this will raise an error in the future.
  mat3 == mat4 # comparison of arrays of different shapes


False

## Broadcasting
Changing shapes of arrays so that we can perform operations on 2 arrays

### Flattening

In [46]:
# Converting 2D array into 1D array using ravel()
a = np.array([[1,2,3], [4,5,6]])
a

array([[1, 2, 3],
       [4, 5, 6]])

In [49]:
np.ravel(a) # to do inpace, a.ravel()

array([1, 2, 3, 4, 5, 6])

In [51]:
# Transposing array

a.T

array([[1, 4],
       [2, 5],
       [3, 6]])

In [53]:
# Reshaping array

b = np.array([1,2,3,4,5,6])

In [55]:
c = b.reshape((2,3)) # 2 rows, 3 columns

In [58]:
c

array([[1, 2, 3],
       [4, 5, 6]])

In [59]:
np.shares_memory(b,c) 

True

In [63]:
# Array sorting 
a = np.array([4,3,1,2])
np.sort(a)

array([1, 2, 3, 4])

In [67]:
# sorting with fancy indexing
# this returns original index of array but after sorting
np.argsort(a)

array([2, 3, 1, 0], dtype=int64)

In [68]:
a

array([4, 3, 1, 2])